# Generated by Django 4.2 on 2024-10-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('deferred', 'Deferred'), ('delivered', 'Delivered'), ('autoresponded', 'Autoresponded'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('complained', 'Complained'), ('unsubscribed', 'Unsubscribed'), ('subscribed', 'Subscribed'), ('unknown', 'Unknown')], max_length=32)),
                ('message_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(blank=True, help_text='Timestamp of webhook notification', null=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reject_reason', models.CharField(blank=True, choices=[('invalid', 'Invalid'), ('bounced', 'Bounced'), ('timed_out', 'Timed Out'), ('blocked', 'Blocked'), ('spam', 'Spam'), ('rejected', 'Rejected'), ('unsubscribed', 'Unsubscribed'), ('other', 'Other')], max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('mta_response', models.TextField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('click_url', models.URLField(blank=True, null=True)),
                ('esp_event', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mail Delivery',
                'verbose_name_plural': 'Mail Deliveries',
            },
        ),
    ]
