# Generated by Django 4.2.29 on 2026-09-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anymail_status_tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailDeliveryEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("esp_name", models.CharField(max_length=64)),
                ("message_id", models.CharField(max_length=255)),
                ("recipient", models.EmailField(max_length=254)),
                (
                    "event_id",
                    models.CharField(
                        help_text="Unique notification id from the ESP (e.g. SNS MessageId); used for idempotency",
                        max_length=255,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                            ("deferred", "Deferred"),
                            ("delivered", "Delivered"),
                            ("autoresponded", "Autoresponded"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("complained", "Complained"),
                            ("unsubscribed", "Unsubscribed"),
                            ("subscribed", "Subscribed"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(blank=True, help_text="Event timestamp reported by the ESP", null=True),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "reject_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("invalid", "Invalid"),
                            ("bounced", "Bounced"),
                            ("timed_out", "Timed Out"),
                            ("blocked", "Blocked"),
                            ("spam", "Spam"),
                            ("rejected", "Rejected"),
                            ("unsubscribed", "Unsubscribed"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                ("mta_response", models.TextField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                ("click_url", models.URLField(blank=True, null=True)),
                ("esp_event", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Mail Delivery Event",
                "verbose_name_plural": "Mail Delivery Events",
                "ordering": ("received_at", "pk"),
            },
        ),
        migrations.AddIndex(
            model_name="maildeliveryevent",
            index=models.Index(fields=["esp_name", "message_id", "recipient"], name="maildeliveryevent_key_idx"),
        ),
        migrations.AddConstraint(
            model_name="maildeliveryevent",
            constraint=models.UniqueConstraint(
                fields=("esp_name", "event_id"), name="maildeliveryevent_unique_esp_event_id"
            ),
        ),
    ]
